app = "asistente-whatsapp"
primary_region = "eze"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[[mounts]]
  source = "wwebjs_session"
  destination = "/app/session"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2