# fly.toml app configuration file
app = "asistente-whatsapp"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[[mounts]]
  source = "wwebjs_session"
  destination = "/app/session"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2
