# fly.toml app configuration file generated for whatsapp-bot-limpio on 2025-06-21T01:46:02-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whatsapp-bot-limpio'
primary_region = 'eze'

[build]
  dockerfile = "Dockerfile"

  [mounts]
source = "wwebjs_auth_vol"
destination = "/app/session"

[http_service]
  internal_port = 3000
  force_https = true

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2
