# fly.toml app configuration file generated for whatsapp-bot-limpio-wispy-haze-7452 on 2025-06-28T09:57:52-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whatsapp-bot-limpio-wispy-haze-7452'
primary_region = 'eze'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'wwebjs_auth_vol'
  destination = '/app/session'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'get'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
