app = "asistente-whatsapp"  # Añada esta línea con el nombre de su aplicación

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
