app = "asistente-whatsapp"
primary_region = "eze"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"

[[mounts]]
  source = "wwebjs_session"
  destination = "/app/session"

[vm]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2

[processes]
  app = "/start.sh"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  processes = ["app"]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [services.http_checks]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    timeout = "5s"
    path = "/health"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20
